### ISSUE TITLE
Incorrect form field in LoginForm

### ISSUE THREAD

**Issue by natmlt** [narenaryan/django-auth-pattern#1]
The comment option on your blog isn't loading so I thought this would be a good way to let you know about the two issues I found while working through your tutorial.  I could do a pull request for one issue but it's a simple change so it's probably easier to just tell you about it:

In log/forms.py the password item should be widget=forms.PasswordInput() not widget=forms.TextInput() so that the password isn't visible when the user is typing it.

The second issue isn't in the completed code.  It only appears in one of the code examples as you step through building the authtest/urls.py.  The code block right under the heading "Adding Login to urls.py" is missing the closing parenthesis after the curly braces on line 10.  It isn't even something I should have noticed and the next change to the file fixes it but I thought you might like to know.

Thanks for writing up a clear and easy to follow example of using the built-in authentication with Bootstrap.  I've been searching and working through tons of examples and tutorials and yours was the first that had exactly what I needed.  It was awesome to not have to first work through pages of tutorial steps about Django basics since so many other tutorials already do that.  It was really useful that you included using Bootstrap and the simplicity of your tutorial made it easier for me to understand it better than all the other tutorials I've done.  Thanks for your time and effort!

**Comment by narenaryan** [comment]
Yeah. thanks, Moriah. I changed it. I fixed that thing. I missed it completely.
